python: add __init__ to gmon module
Ganglia cook-news script was failing with:

Traceback (most recent call last):
  File "/opt/ganglia/bin/cook-news", line 136, in <module>
    import gmon.ganglia
ImportError: No module named gmon.ganglia

We were missing the __init__.py file so that gmond could
be loaded